---
# tasks file for agent
- name: Install requierments
  apt: name=xinetd state=present
  when: not check_mk_agent_over_ssh

- name: Enable xinetd on boot
  service: name=xinetd state=started enabled=yes
  when: not check_mk_agent_over_ssh

# TODO(elnappo): Make URL changeable
#- name: Download check_mk agent deb package
#  get_url: url=https://mathias-kettner.de/download/{{ check_mk_agent_deb_package }} dest=/root/{{ check_mk_agent_deb_package }} validate_certs=no

- name: Copy check_mk agent deb package
  copy: src={{ check_mk_agent_deb_package }} dest=/root/check_mk_agent.deb

- name: Install deb package
  apt: deb=/root/check_mk_agent.deb

- name: Setup SSH key
  authorized_key: user=root key_options='command="/usr/bin/check_mk_agent",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc' key="{{ lookup('file', check_mk_agent_pubkey_file) }}"
  when: check_mk_agent_over_ssh and check_mk_agent_pubkey_file

- name: Install plugin requierments
  apt: name={{ item }} state=present
  with_items: "{{ check_mk_agent_plugins_requirements }}"
 
- name: Copy plugins
  copy: src=plugins/{{ item }} dest=/usr/lib/check_mk_agent/plugins/{{ item }} owner=root group=root mode=0755
  with_items: "{{ check_mk_agent_plugins }}"
